global:
  scrape_interval: 15s  # How often to scrape metrics
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']  # PostgreSQL exporter port

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:9216']  # MongoDB exporter port

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']  # Redis exporter port

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']  # Kafka exporter port

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']  # Neo4j exporter port