version: '3.8'

services:
  # Existing services (postgres, mongodb, qdrant, etc.) remain unchanged...

  # MongoDB Exporter
  mongodb_exporter:
    image: percona/mongodb_exporter:latest
    container_name: ${PROJECT_NAME}-mongodb-exporter
    environment:
      MONGODB_URI: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017"
    ports:
      - "9216:9216"
    depends_on:
      - mongodb
    networks:
      - ${PROJECT_NAME}-network

  # Kafka Exporter
  kafka_exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: ${PROJECT_NAME}-kafka-exporter
    environment:
      KAFKA_BROKERS: "kafka:9092"
    ports:
      - "7071:7071"
    depends_on:
      - kafka
    networks:
      - ${PROJECT_NAME}-network

  # Redis Exporter
  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: ${PROJECT_NAME}-redis-exporter
    environment:
      REDIS_ADDR: "redis://redis:6379"
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - ${PROJECT_NAME}-network

  # Neo4j Exporter (using Neo4j's built-in Prometheus plugin)
  neo4j:
    image: neo4j:latest
    container_name: ${PROJECT_NAME}-neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["apoc", "prometheus"]'  # Enable Prometheus plugin
    volumes:
      - neo4j-data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
      - "2004:2004"  # Prometheus metrics endpoint
    networks:
      - ${PROJECT_NAME}-network

  # Prometheus and Grafana remain unchanged...